---
- hosts: localhost

  tasks:
  - name: Stop running container
    command: docker stop customcontainer
    ignore_errors: True

  - name: Remove container
    command: docker rm customcontainer
    ignore_errors: True

  - name: Remove image
    command: docker rmi customimage
    ignore_errors: True

  - name: Create image customimage
    command: docker build -t customimage .

  - name: Create container customcontainer
    command: docker run -d -p 8080:80 --name customcontainer customimage
